//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("IntelliFlo Ltd")]
[assembly: System.Reflection.AssemblyProduct("JustSaying")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ©2017 IntelliFlo Ltd")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("1.2.3.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.2.3.033ab5c90e3422204b5c576dfa2db4359dde0d65")]


